---
- name: Get idle delay value
  command: "gsettings get org.gnome.desktop.session idle-delay"
  changed_when: false
  register: delay_value

- name: Configure idle delay to infinity
  command: "dbus-launch --exit-with-session gsettings set org.gnome.desktop.session idle-delay 0"
  when: delay_value.stdout != "uint32 0"

- name: Get locked screen state
  command: "gsettings get org.gnome.desktop.screensaver lock-enabled"
  changed_when: false
  register: screen_lock_enable

- name: Disable lock screen
  command: "dbus-launch --exit-with-session gsettings set org.gnome.desktop.screensaver lock-enabled false"
  when: screen_lock_enable.stdout != "false"
