---

- name: Disable screen locking
  become_user: "{{ aivi_user_name }}"
  import_tasks: lock_session.yml
  tags: session

- name: Enable screen keyboard
  import_tasks: screen_keyboard.yml
  tags: keyboard

- name: Add touchscreen calibration tool
  import_tasks: touchscreen_calibration.yml
  tags: screen_calibration

- name: Configure screen mirroring
  import_tasks: mirroring_configuration.yml
  tags : screen_mirroring
