---

- name: Set locale language to CA utf-8
  lineinfile:
    path: /etc/locale.conf
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
    state: present
    create: true
  loop:
    - { regexp: '^LANG=.*$', line: 'LANG=en_US.UTF-8' }
    - { regexp: '^LC_ALL=.*$', line: 'LC_ALL=en_US.UTF-8' }
